import {
  Sparkles,
  Hammer,
  Target,
  Zap,
  BookOpen,
  RefreshCw,
  GitBranch,
  TestTube,
  FileText,
  CheckCircle2,
} from 'lucide-react';
import { SubGenieConfig } from '@/components/genie-widgets';

export const GENIE_CONFIGS: Record<'wishh' | 'forge' | 'review', SubGenieConfig> = {
  wishh: {
    id: 'wishh',
    name: 'Wishh (Planner)',
    columnStatus: 'todo',
    icon: Sparkles,
    color: 'purple',
    workflows: [
      {
        id: 'refine_spec',
        label: 'Refine Spec',
        description: 'Refine task specification and requirements',
        icon: BookOpen,
        genieType: 'wishh',
        columnStatus: 'todo',
      },
      {
        id: 'analyze_deps',
        label: 'Analyze Dependencies',
        description: 'Identify task dependencies and blockers',
        icon: Zap,
        genieType: 'wishh',
        columnStatus: 'todo',
      },
      {
        id: 'create_from_idea',
        label: 'Create from Idea',
        description: 'Convert rough idea into structured task',
        icon: Sparkles,
        genieType: 'wishh',
        columnStatus: 'todo',
      },
      {
        id: 'prioritize',
        label: 'Prioritize',
        description: 'Reorder tasks by priority',
        icon: Target,
        genieType: 'wishh',
        columnStatus: 'todo',
      },
    ],
    skills: [
      {
        id: 'quick_analysis',
        name: 'Quick Analysis',
        description: 'Fast mode (skip deep analysis)',
        icon: Zap,
        genieType: 'wishh',
        defaultEnabled: false,
      },
      {
        id: 'auto_tag',
        name: 'Auto-Tag',
        description: 'Automatically tag tasks by type',
        icon: BookOpen,
        genieType: 'wishh',
        defaultEnabled: false,
      },
    ],
  },

  forge: {
    id: 'forge',
    name: 'Forge (Executor)',
    columnStatus: 'inprogress',
    icon: Hammer,
    color: 'orange',
    workflows: [
      {
        id: 'start_build',
        label: 'Start Build',
        description: 'Initiate code generation or build process',
        icon: Hammer,
        genieType: 'forge',
        columnStatus: 'inprogress',
      },
      {
        id: 'run_tests',
        label: 'Run Tests',
        description: 'Execute test suite',
        icon: TestTube,
        genieType: 'forge',
        columnStatus: 'inprogress',
      },
      {
        id: 'update_status',
        label: 'Update Status',
        description: 'Get execution status and logs',
        icon: RefreshCw,
        genieType: 'forge',
        columnStatus: 'inprogress',
      },
      {
        id: 'create_branch',
        label: 'Create Branch',
        description: '(Git Agent) Create feature branch',
        icon: GitBranch,
        genieType: 'forge',
        columnStatus: 'inprogress',
        externalAgent: 'git_agent',
      },
      {
        id: 'sync_branch',
        label: 'Sync Branch',
        description: '(Git Agent) Sync with main',
        icon: RefreshCw,
        genieType: 'forge',
        columnStatus: 'inprogress',
        externalAgent: 'git_agent',
      },
    ],
    skills: [
      {
        id: 'fast_mode',
        name: 'Fast Mode',
        description: 'Skip non-essential checks, build faster',
        icon: Zap,
        genieType: 'forge',
        defaultEnabled: false,
      },
      {
        id: 'verbose_logs',
        name: 'Verbose Logs',
        description: 'Show all build output',
        icon: FileText,
        genieType: 'forge',
        defaultEnabled: false,
      },
    ],
  },

  review: {
    id: 'review',
    name: 'Review (Validator)',
    columnStatus: 'inreview',
    icon: Target,
    color: 'blue',
    workflows: [
      {
        id: 'run_qa',
        label: 'Run QA Suite',
        description: 'Execute quality assurance tests',
        icon: TestTube,
        genieType: 'review',
        columnStatus: 'inreview',
      },
      {
        id: 'generate_summary',
        label: 'Generate Summary',
        description: 'Auto-generate code review summary',
        icon: FileText,
        genieType: 'review',
        columnStatus: 'inreview',
      },
      {
        id: 'approve_move',
        label: 'Approve & Move',
        description: 'Approve task and move to Done',
        icon: CheckCircle2,
        genieType: 'review',
        columnStatus: 'inreview',
      },
      {
        id: 'request_changes',
        label: 'Request Changes',
        description: 'Flag issues for rework',
        icon: RefreshCw,
        genieType: 'review',
        columnStatus: 'inreview',
      },
    ],
    skills: [
      {
        id: 'express_review',
        name: 'Express Review',
        description: 'Fast-track approval for low-risk changes',
        icon: Zap,
        genieType: 'review',
        defaultEnabled: false,
      },
      {
        id: 'detailed_report',
        name: 'Detailed Report',
        description: 'Generate comprehensive review report',
        icon: FileText,
        genieType: 'review',
        defaultEnabled: false,
      },
    ],
  },
};
