// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureMaturity } from "./FeatureMaturity";

/**
 * A beta feature with merged config + state
 */
export type BetaFeature = { id: string, name: string, description: string, maturity: FeatureMaturity, enabled: boolean, };
