// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Feature maturity level
 */
export type FeatureMaturity = "experimental" | "beta" | "stable";
